CREATE TABLE Usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    grupoDeUsuario VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL
);